### ISSUE TITLE
please provide the files named '/some-page.html'

### ISSUE THREAD

**Issue by kinshasa** [R1ZZU/react-native-webview-messaging#1]
same as title.

**Comment by R1ZZU** [comment]
I was about to add example folder with fully working RN app demonstrating how this module could be used, but sure, more detailed readme is also a thing 😏

**Comment by R1ZZU** [comment]
[Check this out](https://github.com/R1ZZU/react-native-webview-messaging/tree/master/example)! Hope this is good enough to get started 😄
