### ISSUE TITLE
Unexpected token / in JSON at postion 0

### ISSUE THREAD

**Issue by reggie3** [R1ZZU/react-native-webview-messaging#11]
Receiving the following error when using "braintree-web-drop-in" module in react native webview.
![screenshot_20170825-171546](https://user-images.githubusercontent.com/7347192/29733151-da86c3f4-89b9-11e7-8e77-b88fae0b9be3.png)

The error happens when filling in a submit box on the form that the braintree plug in creates.
The code in the webview index.tpl.html is as follows:
```
import RNMessageChannel from "./react-native-webview-messaging";
const dropin = require("braintree-web-drop-in");

const button = document.querySelector("#submit-button");
let clientToken = "";

RNMessageChannel.on("json", json => {
  clientToken = json.clientToken;

  dropin
    .create({
      authorization: clientToken,
      container: "#dropin-container"
    })
    .then(instance => {
      // alert(`instance: ${JSON.stringify(instance)}`);
      button.addEventListener("click", function() {
        instance.requestPaymentMethod(function(err, payload) {
          // Submit payload.nonce to your server
            //alert(`payload: ${JSON.stringify(payload)}`);
        });
      });
    })
    .catch(function(err) {
      // Handle any errors that might've occurred when creating Drop-in
      console.error(err);
    });
});
```

I've gotten the react-native-webview-messaging example expo project to work.  It seems like braintree's library is sending an emit upon form update that I would like react-native-webview-messaging to ignore.  Unfortunately, I can't create a working "console log" or "alert" inside the RNWM's emit function to see what is being set to it.  I think that if I can see what is being set to it, I can figure out some way to ignore it.  Do you have any ideas that would give me insight into what is being emitted.

**Comment by reggie3** [comment]
I figured it out.  Braintree was emitting an event that was being picked up in the react-native-webview-messaging/WebView component.  The data from the event.nativeEvent object was a string that began with "/event/{..." the beginning portion is what was screwing it up.

What do you think about wrapping the JSON.parse(data) call in a try/catch in attempt to avoid errors like this?  I tried it on a local version and it seemed to work.

**Comment by R1ZZU** [comment]
@reggie3 sorry for long reply, could you please provide exact object which causes this error?

**Comment by reggie3** [comment]
I hope your vacation was nice.
The problem is caused when a webview contains code that emits a message itself.  For example, the following code in the Braintree JavaScript SDK can be put into a WebView (via the source prop) in order to display a payment form:
```
<head>
  <meta charset="utf-8">
  <script src="https://js.braintreegateway.com/web/dropin/1.7.0/js/dropin.min.js"></script>
</head>
<body>
  <div id="dropin-container"></div>
  <button id="submit-button">Request payment method</button>
  <script>
    var button = document.querySelector('#submit-button');

    braintree.dropin.create({
      authorization: 'CLIENT_TOKEN_FROM_SERVER',
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function () {
        instance.requestPaymentMethod(function (err, payload) {
          // Submit payload.nonce to your server
        });
      });
    });
  </script>
</body>
```

The form that is displayed includes a submit button that executes the code in the event listener.  The code that is activated on click emits an event on its own as part of the Braintree SDK's code.  The user is unable to control the format of that event.  I don't have the full message available to me right now, but it begins with "/event/{..." which does not match react-native-webview-messaging's expected format for an event.  This results in the attempt to parse the event on line 29 of your library's WebView.js file failing with the above error.

However, wrapping that `JSON.parse(data)` call along with the switch statement that follows in a try/catch statement keeps the error from happening.

**Comment by R1ZZU** [comment]
I'd better add unique hash to messages posted using `send`/`sendJson`/`emit` and check this hash in RN WebView to avoid confusion in case someone will post actual json with `type` field using `window.postMessage`. This approach seems more accurate as it fixes one more potential issue + try/catch could affect performance

**Comment by R1ZZU** [comment]
could you also give me short overview of how are going to combine this module with Braintree SDK? This seems quite tricky to me and I'd expect more difficulties 😞

**Comment by reggie3** [comment]
Now that you mention it, only using the try/catch might result in unexpected messages being received.  However, how would you package a hash in such a way that it can be decoded without potentially trying to JSON.parse something that isn't JSON?

I was working on a picture for a blog post to describe the process, so hopefully that will do a better job of explaining how I plan to use this module with Braintree.  The bolded & underlined actions are what I plan to use your module for.

![picture1](https://user-images.githubusercontent.com/7347192/29929823-9540f8e8-8e3a-11e7-8313-2b03e1233544.png)

**Comment by R1ZZU** [comment]
> how would you package a hash in such a way that it can be decoded without potentially trying to JSON.parse something that isn't JSON?

I'd implement smth like this

Stringify:

```javascript
const dataToEmit = { a: 1};
const stringified = JSON.stringify(dataToEmit);
const withHash = SOME_MAGIC_VALUE + stringified;
window.postMessage(withHash);
```

Parse:

```javascript
if (data.indexOf(SOME_MAGIC_VALUE) !== 0) {
    return; // that's not something that was received from rn messages channel
}

const jsonString = data.replace(SOME_MAGIC_VALUE, '');
const parsed = JSON.parse(jsonString);
```

Thanks for illustration, now it's more clear 👍

**Comment by reggie3** [comment]
That's a pretty cool solution!

**Comment by reggie3** [comment]
SOME_MAGIC_VALUE doesn't need to change, it can be hardwired into your library, correct?  It just has to be something unique that isn't likely to be created by some other library.  Would a GUID suffice?

**Comment by R1ZZU** [comment]
Yes, you're right. Sorry, had no spare time to address this issue yet 😞

**Comment by reggie3** [comment]
I'll submit a pull request with using a GUID and your technique above.
