### ISSUE TITLE
Android 4.4.4 below, react native cannot call the web side method

### ISSUE THREAD

**Issue by TrustTheBoy** [R1ZZU/react-native-webview-messaging#14]
Android 4.4.4 below, react native cannot call the web side method
react native ：0.45+

**Comment by R1ZZU** [comment]
@TrustTheBoy  Could you please provide a code example?
As far as I can see Android 4.4 already uses chromium based webview implementation, so it should work fine

**Comment by R1ZZU** [comment]
@TrustTheBoy any updates?
