### ISSUE TITLE
Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present

### ISSUE THREAD

**Issue by willuke92** [R1ZZU/react-native-webview-messaging#15]
Original message: Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.

I'm getting this error when I try to use this package with React js. Please help. thanks.

**Comment by R1ZZU** [comment]
Root cause is facebook/react-native/issues/11594
I believe you're trying to send smth from webview to rn right after webview loaded, but I'd better use `onLoad` prop for this purposes

**Comment by R1ZZU** [comment]
@willuke92 this one is fixed in [v2](https://github.com/R1ZZU/react-native-webview-messaging/tree/v2). Still need to polish things, add docs, so for now check out v2 examples as a reference on how to use new version
