### ISSUE TITLE
(V1) Cannot run on Android

### ISSUE THREAD

**Issue by ftewman** [R1ZZU/react-native-webview-messaging#19]
I try to run
> npm run android

But it returned error.
> undefined is not a function (evaluating 
'ReactComponentTreeHook.purgeUnmountedComponent()')

**Comment by R1ZZU** [comment]
thanks for raising this up, I'll investigate this issue

**Comment by R1ZZU** [comment]
Most likely you're experiencing this issue due to invalid version of `react` being installed as peer to `react-native`. Try to reinstall `node_modules` and make sure you're installing correct version of `react`
