### ISSUE TITLE
Android Javascript injection not working.

### ISSUE THREAD

**Issue by 468910** [R1ZZU/react-native-webview-messaging#2]
Hey thanks for the cool module its working perfectly for us on IOS.
However its not working on Android.
We have tried multiples devices/simulators and even after manually adding the injected code to window its still not functioning. I tried loading it in various places in my code and even adding it to the Web view directly but it seems its not working at all. This might be related to react-native however. Did you have any experience like this?

**Comment by R1ZZU** [comment]
Hey,
Thanks for feedback!
Could you please share your code example which is not working for you? Might be some non-trivial case or smth. Android version works fine for me, so need to investigate your issue

**Comment by R1ZZU** [comment]
Might be realted to facebook/react-native#11594

**Comment by R1ZZU** [comment]
Check out [this](https://github.com/R1ZZU/react-native-webview-messaging/tree/master/examples/react-native) example. Tested it on android, work fine (however I had no chance to launch expo example on android, but actually I had never able to make android work with expo on my dev machine 😀)

**Comment by 468910** [comment]
Okay was just writing up an explanation, but now I will look into this.

![image](https://user-images.githubusercontent.com/7303197/28930750-e4e06ace-78ae-11e7-917b-828bcd4077cc.png)

The screenshot shows that the RNMessageChannel is there (the reference is always RnMessageChannel.window even though its imported in  React as RNMsgChannel). 
So the message channel is loaded but its not reachable by the code on time which goes back to the issue you referred to.

React
![image](https://user-images.githubusercontent.com/7303197/28930772-fb132020-78ae-11e7-9ea5-b141df807af5.png)

React-Native
![image](https://user-images.githubusercontent.com/7303197/28930796-09ffb940-78af-11e7-8cda-166355f60b1a.png)

No non-trivial usecase so far, just connecting native components like facebook, firebase IAP etc.

**Comment by R1ZZU** [comment]
can you also share your `import` statement of message channel? (webview js, not react native)

**Comment by 468910** [comment]
In our React Project:
import RNMsgChannel from "react-native-webview-messaging";

Also tried 
const RNMsgChannel =  window.RNMessageChannel

quick note you used RNMessagesChannel in the readme, RNMessageChannel.window for exporting and RNMsgChannel in importing :smile:

**Comment by R1ZZU** [comment]
the reason why you can't reach `RNMsgChannel` variable from devtools console is that webpack wraps each module into function and this prevents variable from leaking to global scope. If you want to have access to this variable, make explicit assignment to window.

```javascript
import WhateverNameYouLike from 'react-native-webview-messaging';

window.WhateverNameYouLike = WhateverNameYouLike;
```

---
> quick note you used RNMessagesChannel in the readme, RNMessageChannel.window for exporting and RNMsgChannel in importing 😄

The reason why I've used different naming in example is to demonstrate that you can name this channel whatever you like, it'd still be working. Ideally you shouldn't be aware of global variable named `RNMessagesChannel` and take it in account. Use commonjs/es6 modules and names you like 😄

**Comment by 468910** [comment]
Yeah thats what i figured thats why I'm wondering why you asked about the import as the module always exports to window.RNmessageChannel. That screenshot shows some late night programming ;) However it displays the problem thats why i attached it.

**Comment by R1ZZU** [comment]
Thanks for highlighting this issue and welcome `v0.4.1` 😏 

BTW, was your android issue resolved?

**Comment by 468910** [comment]
Not yet we are going to try the timeout and try your example. I will update here asap.

**Comment by 468910** [comment]
![screenshot_1501862930](https://user-images.githubusercontent.com/7303197/28976853-8cdab768-797a-11e7-99c1-2d0e75a816df.png)

Example gives me this warning.
ran react-native link.

**Comment by R1ZZU** [comment]
Is it example from this repo as is or did you add some modules you use in your app?

**Comment by 468910** [comment]
Just the example as is.

**Comment by R1ZZU** [comment]
`react-native --version`

**Comment by 468910** [comment]
react-native-cli: 2.0.1
react-native: 0.47.1

Anyway I gave up iIopted to rewrite our wrapper in Native Android.
This is working for me with the same React Setup I was using.
I still haven't been able able to fix it for now i wont spend anymore time on this however.

**Comment by R1ZZU** [comment]
Most likely you have some issues with your dev env as I've tested android setup on 2 machines and everything works as expected...

**Comment by R1ZZU** [comment]
Most likely you have some issues with your dev env as I've tested android setup on 2 machines and everything works as expected...
