### ISSUE TITLE
file miss

### ISSUE THREAD

**Issue by Xixi20160512** [R1ZZU/react-native-webview-messaging#24]
### Platform

- [ ] Android
- [ ] iOS

### Issue details

![image](https://user-images.githubusercontent.com/19320239/42854589-112094f6-8a6f-11e8-9d04-d70f0388ebb1.png)

thanks for the package, but after I clone it to my computer,I found  ``BasicExample.html`` is inexistence

**Comment by R1ZZU** [comment]
@Xixi20160512 please run `npm run build` and `npm run examples:build`
