### ISSUE TITLE
Doesn't seem to work on iOS 9.3

### ISSUE THREAD

**Issue by dave-irvine** [R1ZZU/react-native-webview-messaging#3]
Installed and ran the example, both the native and the webview are shown, but clinking the links in native and clicking the buttons in the webview both do nothing.

Works fine in 10.2

**Comment by R1ZZU** [comment]
most likely this happens because safari 9 doesn't support arrow functions used in web example. will check it in a moment and confirm if this assumption is correct

**Comment by R1ZZU** [comment]
Yep. safari 9 doesn't support both [arrow functions](https://caniuse.com/#search=arrow%20function) and [const](https://caniuse.com/#search=const) used in example. Fix is already pushed f2c876d567787378ce10fad002193096831d848c. Could you please test it and let me know if it works as expected now? (I don't have ios 9.3 simulator installed 😒)

**Comment by dave-irvine** [comment]
👍 looks good!
