### ISSUE TITLE
react-native bundling fails when `require`-ing a html file

### ISSUE THREAD

**Issue by dave-irvine** [R1ZZU/react-native-webview-messaging#5]
I have no idea why this works in your Expo example but not in my normal react-native project, but when I do

```
<WebView source={require('./webview.html')} style={{ flex: 1, borderWidth: 2, borderColor: 'red' }} ref={this._refWebView}/>
```

I get the following error:

> Bundling `index.ios.js`  0.0% (0/1), failed.
> SyntaxError:
> ../src/components/Header/components/webview.html: Unexpected token (1:1)

    1 | <!DOCTYPE html>
      |  ^
    2 | <html lang="en">
    3 | <head>
    4 |   <meta charset="UTF-8">

**Comment by dave-irvine** [comment]
To be honest it seems like something is trying to parse the html. If I take out the !DOCTYPE, error changes to:

```
Unexpected token, expected } (9:16)
   7 |   <style>
   8 |     body {
>  9 |       text-align: center;
     |                 ^
  10 |     }
  11 |   </style>
  12 | </head>
```

**Comment by R1ZZU** [comment]
Check out [this](https://github.com/R1ZZU/react-native-webview-messaging/tree/master/examples/react-native) example. Tested both android and ios, works fine 😏

**Comment by R1ZZU** [comment]
No idea why in your case react native fails to require `.html` 😞

**Comment by R1ZZU** [comment]
Can you create a test repo demonstrating your issue? I'd take a look and try to help

**Comment by dave-irvine** [comment]
I'll give yours a go and see what I get

**Comment by dave-irvine** [comment]
-.- for reasons I don't know (and this seems to happen more than I like), killing the simulator, packager, and restarting everything has fixed the problem.
