### ISSUE TITLE
onPermissionRequest

### ISSUE THREAD

**Issue by dave-irvine** [R1ZZU/react-native-webview-messaging#6]
I'm guessing because you are basically superclassing the native WebView, this component is also susceptible to this issue: https://github.com/facebook/react-native/issues/11610 ?

Any chance you could extend your implementation somehow to allow this?

**Comment by R1ZZU** [comment]
I don't believe this is possible without native code tweaking. This module tends to be simple wrapper over native rn webview

**Comment by dave-irvine** [comment]
:( Ok, no problem.
