### ISSUE TITLE
"Module JSTimersExecution is not a registered callable module (calling callTimers)" Error

### ISSUE THREAD

**Issue by reggie3** [R1ZZU/react-native-webview-messaging#8]
I'm getting the following error when trying to run the expo example using Expo version 20:
![screenshot_20170820-133604](https://user-images.githubusercontent.com/7347192/29497440-944bd080-85b5-11e7-938a-253537f8867e.png)

I've updated the package.json file as directed in this post from Expo.io [https://blog.expo.io/expo-sdk-v20-0-0-is-now-available-79f84232a9d1](https://blog.expo.io/expo-sdk-v20-0-0-is-now-available-79f84232a9d1)

resulting in a package.json file that looks like this:
```
{
  "name": "react-native-webview-messaging_example",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~20.0.0",
    "react-native-scripts": "1.1.0",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "build-web": "webpack --progress"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "babel-loader": "^7.1.1",
    "babel-preset-env": "^1.6.0",
    "expo": "^20.0.0",
    "html-webpack-inline-source-plugin": "^0.0.9",
    "html-webpack-plugin": "^2.28.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-webview-messaging": "^1.1.0",
    "webpack": "^2.6.1"
  }
}
```

I'm using a Motorola Nexus 6 as the test device, and I have successfully run Expo/react-native projects previously on my current development setup.

**Comment by R1ZZU** [comment]
@reggie3 I believe `sdkVersion` in `app.json` should also be updated to `20.0.0`. If this will work, I'd really appreciate a pull request from you updating expo example to v20 😺

**Comment by reggie3** [comment]
I'll get to work on it.  However, I've run into into several problems with version 20.0.0. so it may take a few days.  
I'd like to do it since it'd be my first ever open source contribution.

**Comment by R1ZZU** [comment]
Let's track your further activity in #9 No rush, take your time 😄 And don't hesitate to ask for help if needed
